### ISSUE TITLE
Crashes when u spectate sometimes.

### ISSUE THREAD

**Issue by philsarisk** [TheLonelySheep/TeamSpectate#3]
Dedicated tmodloader server. Sometimes it says [-1] beside a person u want to spectate then it crashes the game if u click the player

**Comment by NotLe0n** [comment]
Does the server or the client crash? Can you attach a crashlog so I know where the game crashed? Thanks.

**Comment by philsarisk** [comment]
> Does the server or the client crash? Can you attach a crashlog so I know where the game crashed? Thanks.

The client. This has happened with without other mods as well. Definitely not just me cause ive had this issue with multiple playthroughs. This is a crashlog I found from march of this year probably was tModLoader 1.3 but same issue Index out of array as I got today.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TeamSpectate.src.Camera.ModifyScreenPosition() in TeamSpectate\src\Camera.cs:line 17
   at Terraria.ModLoader.PlayerHooks.ModifyScreenPosition(Player player)
   at DMD<Terraria.Main::DoDraw>(Main this, GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

**Comment by NotLe0n** [comment]
I think I know why it crashes and I might have a fix for it. Do you have some consitent method to make it crash or does it happen randomly?

**Comment by TheExploration** [comment]
it seems to happen randomly

**Comment by philsarisk** [comment]
> I think I know why it crashes and I might have a fix for it. Do you have some consitent method to make it crash or does it happen randomly?

It seems to happen randomly. Maybe theres a reason but I havent figured out yet.

**Comment by NotLe0n** [comment]
maybe fixed in [`c4dacfa`](https://github.com/NotLe0n/TeamSpectate/commit/c4dacfafeb1655bc4c7bec29fa9f15eabb9f8488). I'm gonna close this issue now. You can reopen it if the same crash happens again.
